# Generated by Django 5.2 on 2025-04-22 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=10)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), ('Discharge', 'Discharge')], max_length=10)),
                ('ward', models.CharField(choices=[('General', 'General Ward'), ('Pediatrics', 'Pediatrics'), ('ICU', 'Intensive Care Unit'), ('Maternity', 'Maternity Ward'), ('None', 'None')], max_length=20)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
