# Generated by Django 5.1.6 on 2025-02-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='master_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
