# Generated by Django 5.1.6 on 2025-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('room_number', models.CharField(max_length=20)),
                ('bed_number', models.CharField(max_length=20)),
                ('admission_date', models.DateTimeField()),
                ('admission_reason', models.TextField()),
                ('attending_physician', models.CharField(max_length=255)),
                ('attending_nurse', models.CharField(max_length=255)),
            ],
        ),
    ]
