# Generated by Django 5.1.6 on 2025-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='room_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
