# Generated by Django 5.1.6 on 2025-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_employee_master_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='master_key',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
