# Generated by Django 5.1.6 on 2025-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_patient_room_number_patient_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
