# Generated by Django 5.2 on 2025-04-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_medication_nursenotes_vitalsigns2'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='physician_name',
            field=models.CharField(default='Unknown Physician', max_length=100),
        ),
    ]
