# Generated by Django 5.1.6 on 2025-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient')], max_length=20, null=True),
        ),
    ]
