# Generated by Django 5.2 on 2025-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_patientinformation_physician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='physician_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
