# Generated by Django 5.1.6 on 2025-03-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
