# Generated by Django 5.1.6 on 2025-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_patientinformation_physician_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_schedule',
            name='shift_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
