# Generated by Django 5.2 on 2025-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_patientinformation_physician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='ward',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('Pediatrics', 'Pediatrics'), ('ICU', 'Intensive Care Unit'), ('Maternity', 'Maternity Ward'), ('None', 'None')], max_length=20),
        ),
    ]
