# Generated by Django 5.1.6 on 2025-03-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='master_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
