# Generated by Django 5.1.6 on 2025-04-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_patientinformation'),
        ('App', '0005_alter_patient_status'),
    ]

    operations = [
    ]
