# Generated by Django 5.1.6 on 2025-04-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_merge_20250423_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
