# Generated by Django 5.2 on 2025-04-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_patientinformation_ward'),
        ('App', '0006_shift_schedule_shift_password'),
    ]

    operations = [
    ]
