# Generated by Django 5.1.6 on 2025-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_employee_master_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='master_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
