# Generated by Django 5.1.6 on 2025-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
