# Generated by Django 5.2 on 2025-04-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_medication_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
    ]
