# Generated by Django 5.1.6 on 2025-04-27 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_medication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.TextField()),
            ],
        ),
    ]
