# Generated by Django 5.2 on 2025-04-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_nurse_logs'),
        ('App', '0010_patientinformation_number'),
    ]

    operations = [
    ]
