# Generated by Django 5.2 on 2025-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_merge_0010_nurse_logs_0010_patientinformation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
