# Generated by Django 5.2 on 2025-05-01 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_shift_schedule_date_alter_patientinformation_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns2',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
