# Generated by Django 5.2 on 2025-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_vitalsigns2_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns2',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
