# Generated by Django 5.2 on 2025-05-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_vitalsigns2_date_and_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('administered_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Not Taken', 'Not Taken'), ('Administered', 'Administered'), ('Refused', 'Refused')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.patientinformation')),
            ],
        ),
    ]
