# Generated by Django 5.2 on 2025-05-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_medicationlogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationlogs',
            options={'ordering': ['-date_time'], 'verbose_name_plural': 'Medication Logs'},
        ),
        migrations.AddField(
            model_name='medicationlogs',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='App.medication'),
        ),
    ]
