# Generated by Django 5.2 on 2025-05-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_medicationlogs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationlogs',
            name='drug_name',
        ),
    ]
