# Generated by Django 5.2 on 2025-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_remove_medicationlogs_drug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationlogs',
            name='status',
            field=models.CharField(choices=[('administered', 'Administered'), ('not_taken', 'Not Taken'), ('refused', 'Refused')], max_length=20),
        ),
    ]
