# Generated by Django 5.2.1 on 2025-05-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_medicationlogs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns2',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional remarks/ observations', null=True),
        ),
    ]
