# Generated by Django 5.2.1 on 2025-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_vitalsigns2_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when the medication ends or is discontinued', null=True),
        ),
    ]
