# Generated by Django 5.2.1 on 2025-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_medication_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlogs',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
