# Generated by Django 5.1.6 on 2025-05-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_medicationlogs_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vitals_data', models.JSONField()),
                ('medications_data', models.JSONField()),
                ('medication_logs_data', models.JSONField()),
                ('nurse_notes_data', models.JSONField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='App.patientinformation')),
            ],
        ),
    ]
