# Generated by Django 5.1.6 on 2025-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_patientsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsnapshot',
            name='patient_data',
            field=models.JSONField(default=dict),
        ),
    ]
