# Generated by Django 5.1.6 on 2025-05-22 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_medication_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsnapshot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='App.employee'),
        ),
    ]
